# Site
repository: "sproogen/resume-theme"

# Personal info
name: "Priya Nath"
title: "Technology Manager, Data Analyst, AI/ML Enthusiast"
email: "nath.v.priya@gmail.com"
website: "https://nathpriya.github.io/website/"

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: "priya-nath"
twitter_username: "pRiya_nAth_"
github_username: "NathPriya"
instagram_username: "priyanath.13"

# Build settings
remote_theme: "sproogen/resume-theme"

plugins:
  - jekyll-seo-tag
